feat: track user goals with google analytics
polywrap/evo.ninja-fork pull request #15
Opened 2023-08-26 16:51 UTC by rihp

2023-08-26 16:53 UTC, rihp commented
we might have to add a disclaimer before adding this one

2023-08-30 10:49 UTC, nerfZael commented
We should research whether or not we need a disclaimer for this

2023-08-30 10:49 UTC, nerfZael requested changes

2023-08-30 10:49 UTC, nerfZael commented on apps/browser/src/components/Chat/Chat.tsx
> +    // Your existing code
We can remove this :D

2023-08-30 10:49 UTC, nerfZael commented on apps/browser/src/components/Chat/Chat.tsx
> +    // Google Analytics Event Tracking
I'd move this to a separate function in a separate file

2023-08-30 21:34 UTC, nerfZael commented
Looks good, but I think we need the disclaimer :S

2023-08-31 10:50 UTC, rihp commented
I've added a disclaimer at the bottom that has to be agreed to before inputting a goal
<img width="1581" alt="image" src="https://github.com/polywrap/evo.ninja-fork/assets/12145726/e5e42628-a6d9-4d40-8663-111536ffd5b6">

2023-08-31 18:43 UTC, rihp commented
<img width="1192" alt="image" src="https://github.com/polywrap/evo.ninja-fork/assets/12145726/e9416ff4-3630-4703-a42c-591c1d91ea0f">

2023-08-31 19:05 UTC, closed without merging