feat: display a single file for scripts created
polywrap/evo.ninja-fork pull request #3
Opened 2023-08-23 18:39 UTC by rihp

![image](https://github.com/polywrap/evo.ninja/assets/12145726/e9b8da43-a8eb-4e57-97f5-2353e8e13b57)
![image](https://github.com/polywrap/evo.ninja/assets/12145726/0af0eace-f0d7-4571-91b6-00c246436134)

2023-08-23 20:32 UTC, nerfZael requested changes

2023-08-23 20:32 UTC, nerfZael commented on apps/browser/src/components/Sidebar/Sidebar.tsx
> +          {Object.keys(userFilesGrouped).map((name, i) => (
I don't think we should be applying the same logic for workspace files

2023-08-24 07:56 UTC, rihp commented on apps/browser/src/components/Sidebar/Sidebar.tsx
> +          {Object.keys(userFilesGrouped).map((name, i) => (
Updated!

2023-08-24 08:25 UTC, rihp commented
![image](https://github.com/polywrap/evo.ninja-fork/assets/12145726/eda83969-db27-41ec-a144-ee092275177b)
Updated!

2023-08-30 10:56 UTC, nerfZael approved these changes
I'll merge this since it works, but I think the scripts "explorer" should not be a "file explorer"
We should have a separate view for this

2023-08-30 10:56 UTC, merged